In [1]:
print("Hello, Insurance Project!")

Hello, Insurance Project!

In [2]:
import pandas as pd

In [3]:
df = pd.read_excel("../data/Worksheet in Case Study question 2.xlsx")

FileNotFoundError: [Errno 2] No such file or directory: '../data/Worksheet in Case Study question 2.xlsx'

In [6]:
df = pd.read_excel(
    "../data/Worksheet in Case Study question 2.xlsx",
    engine="openpyxl"
)

BadZipFile: File is not a zip file

In [7]:
df = pd.read_excel(
    "../data/Worksheet in Case Study question 2.xlsx",
    engine="openpyxl"
)

In [8]:
df.shape

(1000, 39)

In [9]:
df.columns

Index(['months_as_customer', 'age', 'policy_number', 'policy_bind_date',
       'policy_state', 'policy_csl', 'policy_deductable',
       'policy_annual_premium', 'umbrella_limit', 'insured_zip', 'insured_sex',
       'insured_education_level', 'insured_occupation', 'insured_hobbies',
       'insured_relationship', 'capital-gains', 'capital-loss',
       'incident_date', 'incident_type', 'collision_type', 'incident_severity',
       'authorities_contacted', 'incident_state', 'incident_city',
       'incident_location', 'incident_hour_of_the_day',
       'number_of_vehicles_involved', 'property_damage', 'bodily_injuries',
       'witnesses', 'police_report_available', 'total_claim_amount',
       'injury_claim', 'property_claim', 'vehicle_claim', 'auto_make',
       'auto_model', 'auto_year', 'fraud_reported'],
      dtype='str')

In [10]:
df.head()

,months_as_customer,age,policy_number,policy_bind_date,policy_state,policy_csl,policy_deductable,policy_annual_premium,umbrella_limit,insured_zip,...,witnesses,police_report_available,total_claim_amount,injury_claim,property_claim,vehicle_claim,auto_make,auto_model,auto_year,fraud_reported
0,328,48,521585,2014-10-17,OH,250/500,1000,1406.91,0,466132,...,2,YES,71610,6510,13020,52080,Saab,92x,2004,Y
1,228,42,342868,2006-06-27,IN,250/500,2000,1197.22,5000000,468176,...,0,?,5070,780,780,3510,Mercedes,E400,2007,Y
2,134,29,687698,2000-09-06,OH,100/300,2000,1413.14,5000000,430632,...,3,NO,34650,7700,3850,23100,Dodge,RAM,2007,N
3,256,41,227811,1990-05-25,IL,250/500,2000,1415.74,6000000,608117,...,2,NO,63400,6340,6340,50720,Chevrolet,Tahoe,2014,Y
4,228,44,367455,2014-06-06,IL,500/1000,1000,1583.91,6000000,610706,...,1,NO,6500,1300,650,4550,Accura,RSX,2009,N

In [11]:
df["fraud_reported"].value_counts()

fraud_reported
N    753
Y    247
Name: count, dtype: int64

In [12]:
(df == "?").sum()

months_as_customer               0
age                              0
policy_number                    0
policy_bind_date                 0
policy_state                     0
policy_csl                       0
policy_deductable                0
policy_annual_premium            0
umbrella_limit                   0
insured_zip                      0
insured_sex                      0
insured_education_level          0
insured_occupation               0
insured_hobbies                  0
insured_relationship             0
capital-gains                    0
capital-loss                     0
incident_date                    0
incident_type                    0
collision_type                 178
incident_severity                0
authorities_contacted            0
incident_state                   0
incident_city                    0
incident_location                0
incident_hour_of_the_day         0
number_of_vehicles_involved      0
property_damage                360
bodily_injuries                  0
witnesses                        0
police_report_available        343
total_claim_amount               0
injury_claim                     0
property_claim                   0
vehicle_claim                    0
auto_make                        0
auto_model                       0
auto_year                        0
fraud_reported                   0
dtype: int64

In [13]:
missing_question = (df == "?").sum()
missing_question[missing_question > 0]

collision_type             178
property_damage            360
police_report_available    343
dtype: int64

In [14]:
for col in ["collision_type", "property_damage", "police_report_available"]:
    print("\n", col)
    print(df[col].value_counts(dropna=False))

 collision_type
collision_type
Rear Collision     292
Side Collision     276
Front Collision    254
?                  178
Name: count, dtype: int64

 property_damage
property_damage
?      360
NO     338
YES    302
Name: count, dtype: int64

 police_report_available
police_report_available
?      343
NO     343
YES    314
Name: count, dtype: int64

In [15]:
df.isnull().sum()

months_as_customer              0
age                             0
policy_number                   0
policy_bind_date                0
policy_state                    0
policy_csl                      0
policy_deductable               0
policy_annual_premium           0
umbrella_limit                  0
insured_zip                     0
insured_sex                     0
insured_education_level         0
insured_occupation              0
insured_hobbies                 0
insured_relationship            0
capital-gains                   0
capital-loss                    0
incident_date                   0
incident_type                   0
collision_type                  0
incident_severity               0
authorities_contacted          91
incident_state                  0
incident_city                   0
incident_location               0
incident_hour_of_the_day        0
number_of_vehicles_involved     0
property_damage                 0
bodily_injuries                 0
witnesses                       0
police_report_available         0
total_claim_amount              0
injury_claim                    0
property_claim                  0
vehicle_claim                   0
auto_make                       0
auto_model                      0
auto_year                       0
fraud_reported                  0
dtype: int64

In [16]:
missing = df.isnull().sum()
missing[missing > 0]

authorities_contacted    91
dtype: int64

In [17]:
df = df.replace("?", pd.NA)

In [18]:
df.isnull().sum()

months_as_customer               0
age                              0
policy_number                    0
policy_bind_date                 0
policy_state                     0
policy_csl                       0
policy_deductable                0
policy_annual_premium            0
umbrella_limit                   0
insured_zip                      0
insured_sex                      0
insured_education_level          0
insured_occupation               0
insured_hobbies                  0
insured_relationship             0
capital-gains                    0
capital-loss                     0
incident_date                    0
incident_type                    0
collision_type                 178
incident_severity                0
authorities_contacted           91
incident_state                   0
incident_city                    0
incident_location                0
incident_hour_of_the_day         0
number_of_vehicles_involved      0
property_damage                360
bodily_injuries                  0
witnesses                        0
police_report_available        343
total_claim_amount               0
injury_claim                     0
property_claim                   0
vehicle_claim                    0
auto_make                        0
auto_model                       0
auto_year                        0
fraud_reported                   0
dtype: int64

In [19]:
missing = df.isnull().sum()
missing[missing > 0].sort_values(ascending=False)

property_damage            360
police_report_available    343
collision_type             178
authorities_contacted       91
dtype: int64

In [20]:
missing = df.isnull().sum()
missing[missing > 0].sort_values(ascending=False)

property_damage            360
police_report_available    343
collision_type             178
authorities_contacted       91
dtype: int64

In [21]:
categorical_missing_cols = [
    "property_damage",
    "police_report_available",
    "collision_type",
    "authorities_contacted"
]

for col in categorical_missing_cols:
    df[col] = df[col].fillna("Unknown")

In [22]:
df[categorical_missing_cols].isnull().sum()

property_damage            0
police_report_available    0
collision_type             0
authorities_contacted      0
dtype: int64

In [23]:
df.duplicated().sum()

np.int64(0)

In [24]:
df.dtypes

months_as_customer                      int64
age                                     int64
policy_number                           int64
policy_bind_date               datetime64[us]
policy_state                              str
policy_csl                                str
policy_deductable                       int64
policy_annual_premium                 float64
umbrella_limit                          int64
insured_zip                             int64
insured_sex                               str
insured_education_level                   str
insured_occupation                        str
insured_hobbies                           str
insured_relationship                      str
capital-gains                           int64
capital-loss                            int64
incident_date                  datetime64[us]
incident_type                             str
collision_type                            str
incident_severity                         str
authorities_contacted                     str
incident_state                            str
incident_city                             str
incident_location                         str
incident_hour_of_the_day                int64
number_of_vehicles_involved             int64
property_damage                           str
bodily_injuries                         int64
witnesses                               int64
police_report_available                   str
total_claim_amount                      int64
injury_claim                            int64
property_claim                          int64
vehicle_claim                           int64
auto_make                                 str
auto_model                             object
auto_year                               int64
fraud_reported                            str
dtype: object

In [25]:
df.describe().T

,count,mean,min,25%,50%,75%,max,std
months_as_customer,1000.0,203.954,0.0,115.75,199.5,276.25,479.0,115.113174
age,1000.0,38.948,19.0,32.0,38.0,44.0,64.0,9.140287
policy_number,1000.0,546238.648,100804.0,335980.25,533135.0,759099.75,999435.0,257063.005276
policy_bind_date,1000,2002-02-08 04:40:48,1990-01-08 00:00:00,1995-09-19 00:00:00,2002-04-01 12:00:00,2008-04-21 12:00:00,2015-02-22 00:00:00,NaN
policy_deductable,1000.0,1136.0,500.0,500.0,1000.0,2000.0,2000.0,611.864673
policy_annual_premium,1000.0,1256.40615,433.33,1089.6075,1257.2,1415.695,2047.59,244.167395
umbrella_limit,1000.0,1101000.0,-1000000.0,0.0,0.0,0.0,10000000.0,2297406.598118
insured_zip,1000.0,501214.488,430104.0,448404.5,466445.5,603251.0,620962.0,71701.610941
capital-gains,1000.0,25126.1,0.0,0.0,0.0,51025.0,100500.0,27872.187708
capital-loss,1000.0,-26793.7,-111100.0,-51500.0,-23250.0,0.0,0.0,28104.096686
incident_date,1000,2015-01-30 08:02:24,2015-01-01 00:00:00,2015-01-15 00:00:00,2015-01-31 00:00:00,2015-02-15 00:00:00,2015-03-01 00:00:00,NaN
incident_hour_of_the_day,1000.0,11.644,0.0,6.0,12.0,17.0,23.0,6.951373
number_of_vehicles_involved,1000.0,1.839,1.0,1.0,1.0,3.0,4.0,1.01888
bodily_injuries,1000.0,0.992,0.0,0.0,1.0,2.0,2.0,0.820127
witnesses,1000.0,1.487,0.0,1.0,1.0,2.0,3.0,1.111335
total_claim_amount,1000.0,52761.94,100.0,41812.5,58055.0,70592.5,114920.0,26401.53319
injury_claim,1000.0,7433.42,0.0,4295.0,6775.0,11305.0,21450.0,4880.951853
property_claim,1000.0,7399.57,0.0,4445.0,6750.0,10885.0,23670.0,4824.726179
vehicle_claim,1000.0,37928.95,70.0,30292.5,42100.0,50822.5,79560.0,18886.252893
auto_year,1000.0,2005.103,1995.0,2000.0,2005.0,2010.0,2015.0,6.015861

In [26]:
df.describe().T

,count,mean,min,25%,50%,75%,max,std
months_as_customer,1000.0,203.954,0.0,115.75,199.5,276.25,479.0,115.113174
age,1000.0,38.948,19.0,32.0,38.0,44.0,64.0,9.140287
policy_number,1000.0,546238.648,100804.0,335980.25,533135.0,759099.75,999435.0,257063.005276
policy_bind_date,1000,2002-02-08 04:40:48,1990-01-08 00:00:00,1995-09-19 00:00:00,2002-04-01 12:00:00,2008-04-21 12:00:00,2015-02-22 00:00:00,NaN
policy_deductable,1000.0,1136.0,500.0,500.0,1000.0,2000.0,2000.0,611.864673
policy_annual_premium,1000.0,1256.40615,433.33,1089.6075,1257.2,1415.695,2047.59,244.167395
umbrella_limit,1000.0,1101000.0,-1000000.0,0.0,0.0,0.0,10000000.0,2297406.598118
insured_zip,1000.0,501214.488,430104.0,448404.5,466445.5,603251.0,620962.0,71701.610941
capital-gains,1000.0,25126.1,0.0,0.0,0.0,51025.0,100500.0,27872.187708
capital-loss,1000.0,-26793.7,-111100.0,-51500.0,-23250.0,0.0,0.0,28104.096686
incident_date,1000,2015-01-30 08:02:24,2015-01-01 00:00:00,2015-01-15 00:00:00,2015-01-31 00:00:00,2015-02-15 00:00:00,2015-03-01 00:00:00,NaN
incident_hour_of_the_day,1000.0,11.644,0.0,6.0,12.0,17.0,23.0,6.951373
number_of_vehicles_involved,1000.0,1.839,1.0,1.0,1.0,3.0,4.0,1.01888
bodily_injuries,1000.0,0.992,0.0,0.0,1.0,2.0,2.0,0.820127
witnesses,1000.0,1.487,0.0,1.0,1.0,2.0,3.0,1.111335
total_claim_amount,1000.0,52761.94,100.0,41812.5,58055.0,70592.5,114920.0,26401.53319
injury_claim,1000.0,7433.42,0.0,4295.0,6775.0,11305.0,21450.0,4880.951853
property_claim,1000.0,7399.57,0.0,4445.0,6750.0,10885.0,23670.0,4824.726179
vehicle_claim,1000.0,37928.95,70.0,30292.5,42100.0,50822.5,79560.0,18886.252893
auto_year,1000.0,2005.103,1995.0,2000.0,2005.0,2010.0,2015.0,6.015861

In [27]:
df[df["umbrella_limit"] < 0]["umbrella_limit"].value_counts()

umbrella_limit
-1000000    1
Name: count, dtype: int64

In [28]:
df[df["umbrella_limit"] < 0].T

                                                  290
months_as_customer                                284
age                                                42
policy_number                                  526039
policy_bind_date                  1995-05-04 00:00:00
policy_state                                       OH
policy_csl                                    100/300
policy_deductable                                 500
policy_annual_premium                         1338.54
umbrella_limit                               -1000000
insured_zip                                    438178
insured_sex                                      MALE
insured_education_level                     Associate
insured_occupation                  machine-op-inspct
insured_hobbies                              kayaking
insured_relationship                             wife
capital-gains                                       0
capital-loss                                        0
incident_date                     2015-01-29 00:00:00
incident_type                Single Vehicle Collision
collision_type                         Side Collision
incident_severity                        Major Damage
authorities_contacted                       Ambulance
incident_state                                     NC
incident_city                               Arlington
incident_location                     3936 Tree Drive
incident_hour_of_the_day                           13
number_of_vehicles_involved                         1
property_damage                                   YES
bodily_injuries                                     0
witnesses                                           1
police_report_available                       Unknown
total_claim_amount                              94160
injury_claim                                     8560
property_claim                                  17120
vehicle_claim                                   68480
auto_make                                   Chevrolet
auto_model                                     Malibu
auto_year                                        1996
fraud_reported                                      N

In [29]:
df.loc[df["umbrella_limit"] >= 0, "umbrella_limit"].median()

np.float64(0.0)

In [30]:
df.loc[df["umbrella_limit"] < 0, "umbrella_limit"] = 0

In [31]:
df["umbrella_limit"].min()

np.int64(0)

In [32]:
df.duplicated().sum()

np.int64(0)

In [33]:
df["fraud_reported"].value_counts()

fraud_reported
N    753
Y    247
Name: count, dtype: int64

In [34]:
categorical_cols = df.select_dtypes(include=["object", "str"]).columns

for col in categorical_cols:
    print("\n---", col, "---")
    print(df[col].value_counts().head(15))

--- policy_state ---
policy_state
OH    352
IL    338
IN    310
Name: count, dtype: int64

--- policy_csl ---
policy_csl
250/500     351
100/300     349
500/1000    300
Name: count, dtype: int64

--- insured_sex ---
insured_sex
FEMALE    537
MALE      463
Name: count, dtype: int64

--- insured_education_level ---
insured_education_level
JD             161
High School    160
Associate      145
MD             144
Masters        143
PhD            125
College        122
Name: count, dtype: int64

--- insured_occupation ---
insured_occupation
machine-op-inspct    93
prof-specialty       85
tech-support         78
sales                76
exec-managerial      76
craft-repair         74
transport-moving     72
other-service        71
priv-house-serv      71
armed-forces         69
adm-clerical         65
protective-serv      63
handlers-cleaners    54
farming-fishing      53
Name: count, dtype: int64

--- insured_hobbies ---
insured_hobbies
reading           64
paintball         57
exercise          57
bungie-jumping    56
golf              55
camping           55
movies            55
kayaking          54
yachting          53
hiking            52
video-games       50
base-jumping      49
skydiving         49
board-games       48
polo              47
Name: count, dtype: int64

--- insured_relationship ---
insured_relationship
own-child         183
other-relative    177
not-in-family     174
husband           170
wife              155
unmarried         141
Name: count, dtype: int64

--- incident_type ---
incident_type
Multi-vehicle Collision     419
Single Vehicle Collision    403
Vehicle Theft                94
Parked Car                   84
Name: count, dtype: int64

--- collision_type ---
collision_type
Rear Collision     292
Side Collision     276
Front Collision    254
Unknown            178
Name: count, dtype: int64

--- incident_severity ---
incident_severity
Minor Damage      354
Total Loss        280
Major Damage      276
Trivial Damage     90
Name: count, dtype: int64

--- authorities_contacted ---
authorities_contacted
Police       292
Fire         223
Other        198
Ambulance    196
Unknown       91
Name: count, dtype: int64

--- incident_state ---
incident_state
NY    262
SC    248
WV    217
VA    110
NC    110
PA     30
OH     23
Name: count, dtype: int64

--- incident_city ---
incident_city
Springfield    157
Arlington      152
Columbus       149
Northbend      145
Hillsdale      141
Riverwood      134
Northbrook     122
Name: count, dtype: int64

--- incident_location ---
incident_location
9935 4th Drive        1
6608 MLK Hwy          1
7121 Francis Lane     1
6956 Maple Drive      1
3041 3rd Ave          1
8973 Washington St    1
5846 Weaver Drive     1
3525 3rd Hwy          1
4872 Rock Ridge       1
3066 Francis Ave      1
1558 1st Ridge        1
5971 5th Hwy          1
6655 5th Drive        1
6582 Elm Lane         1
6851 3rd Drive        1
Name: count, dtype: int64

--- property_damage ---
property_damage
Unknown    360
NO         338
YES        302
Name: count, dtype: int64

--- police_report_available ---
police_report_available
Unknown    343
NO         343
YES        314
Name: count, dtype: int64

--- auto_make ---
auto_make
Saab          80
Dodge         80
Suburu        80
Nissan        78
Chevrolet     76
Ford          72
BMW           72
Toyota        70
Audi          69
Accura        68
Volkswagen    68
Jeep          67
Mercedes      65
Honda         55
Name: count, dtype: int64

--- auto_model ---
auto_model
RAM           43
Wrangler      42
A3            37
Neon          37
MDX           36
Jetta         35
Passat        33
A5            32
Legacy        32
Pathfinder    31
Malibu        30
92x           28
Camry         28
Forrestor     28
E400          27
Name: count, dtype: int64

--- fraud_reported ---
fraud_reported
N    753
Y    247
Name: count, dtype: int64

In [35]:
categorical_cols = df.select_dtypes(include=["object", "str"]).columns

for col in categorical_cols:
    print(f"{col}: {df[col].nunique()} unique values")

policy_state: 3 unique values
policy_csl: 3 unique values
insured_sex: 2 unique values
insured_education_level: 7 unique values
insured_occupation: 14 unique values
insured_hobbies: 20 unique values
insured_relationship: 6 unique values
incident_type: 4 unique values
collision_type: 4 unique values
incident_severity: 4 unique values
authorities_contacted: 5 unique values
incident_state: 7 unique values
incident_city: 7 unique values
incident_location: 1000 unique values
property_damage: 3 unique values
police_report_available: 3 unique values
auto_make: 14 unique values
auto_model: 39 unique values
fraud_reported: 2 unique values

In [36]:
df = df.drop(columns=["incident_location"])

In [37]:
df.shape

(1000, 38)

In [38]:
print("policy_number:", df["policy_number"].nunique())
print("insured_zip:", df["insured_zip"].nunique())

policy_number: 1000
insured_zip: 995

In [39]:
df = df.drop(columns=["policy_number", "insured_zip"])

In [40]:
df.shape

(1000, 36)

In [41]:
df = df.drop(columns=["policy_number", "insured_zip"])

KeyError: "['policy_number', 'insured_zip'] not found in axis"

In [42]:
df.shape

(1000, 36)

In [43]:
df.columns.tolist()

['months_as_customer',
 'age',
 'policy_bind_date',
 'policy_state',
 'policy_csl',
 'policy_deductable',
 'policy_annual_premium',
 'umbrella_limit',
 'insured_sex',
 'insured_education_level',
 'insured_occupation',
 'insured_hobbies',
 'insured_relationship',
 'capital-gains',
 'capital-loss',
 'incident_date',
 'incident_type',
 'collision_type',
 'incident_severity',
 'authorities_contacted',
 'incident_state',
 'incident_city',
 'incident_hour_of_the_day',
 'number_of_vehicles_involved',
 'property_damage',
 'bodily_injuries',
 'witnesses',
 'police_report_available',
 'total_claim_amount',
 'injury_claim',
 'property_claim',
 'vehicle_claim',
 'auto_make',
 'auto_model',
 'auto_year',
 'fraud_reported']

In [44]:
missing = df.isnull().sum()
missing[missing > 0]

Series([], dtype: int64)

In [45]:
X = df.drop(columns=["fraud_reported"])

In [46]:
y = df["fraud_reported"]

In [47]:
print("X shape:", X.shape)
print("y shape:", y.shape)

X shape: (1000, 35)
y shape: (1000,)

In [48]:
y = y.map({"N": 0, "Y": 1})

In [49]:
y.value_counts()

fraud_reported
0    753
1    247
Name: count, dtype: int64

In [50]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.20,
    random_state=42,
    stratify=y
)

In [51]:
print("X_train:", X_train.shape)
print("X_test :", X_test.shape)
print("y_train:", y_train.shape)
print("y_test :", y_test.shape)

X_train: (800, 35)
X_test : (200, 35)
y_train: (800,)
y_test : (200,)

In [52]:
numeric_cols = X_train.select_dtypes(include=["int64", "float64"]).columns
categorical_cols = X_train.select_dtypes(include=["object", "str"]).columns

print("Numerical columns:", len(numeric_cols))
print("Categorical columns:", len(categorical_cols))

Numerical columns: 16
Categorical columns: 17

In [53]:
print("\nNumerical:")
print(list(numeric_cols))

print("\nCategorical:")
print(list(categorical_cols))

Numerical:
['months_as_customer', 'age', 'policy_deductable', 'policy_annual_premium', 'umbrella_limit', 'capital-gains', 'capital-loss', 'incident_hour_of_the_day', 'number_of_vehicles_involved', 'bodily_injuries', 'witnesses', 'total_claim_amount', 'injury_claim', 'property_claim', 'vehicle_claim', 'auto_year']

Categorical:
['policy_state', 'policy_csl', 'insured_sex', 'insured_education_level', 'insured_occupation', 'insured_hobbies', 'insured_relationship', 'incident_type', 'collision_type', 'incident_severity', 'authorities_contacted', 'incident_state', 'incident_city', 'property_damage', 'police_report_available', 'auto_make', 'auto_model']

In [54]:
print(X_train[["policy_bind_date", "incident_date"]].head())

    policy_bind_date incident_date
887       2009-07-29    2015-02-19
317       1991-12-06    2015-01-18
796       1990-02-15    2015-01-12
425       2003-05-24    2015-02-12
991       2006-07-12    2015-02-06

In [55]:
for data in [X_train, X_test]:
    data["policy_bind_year"] = data["policy_bind_date"].dt.year
    data["policy_bind_month"] = data["policy_bind_date"].dt.month
    
    data["incident_year"] = data["incident_date"].dt.year
    data["incident_month"] = data["incident_date"].dt.month
    data["incident_day"] = data["incident_date"].dt.day
    
    data["policy_duration_days"] = (
        data["incident_date"] - data["policy_bind_date"]
    ).dt.days

In [56]:
X_train[
    [
        "policy_bind_year",
        "policy_bind_month",
        "incident_year",
        "incident_month",
        "incident_day",
        "policy_duration_days"
    ]
].head()

,policy_bind_year,policy_bind_month,incident_year,incident_month,incident_day,policy_duration_days
887,2009,7,2015,2,19,2031
317,1991,12,2015,1,18,8444
796,1990,2,2015,1,12,9097
425,2003,5,2015,2,12,4282
991,2006,7,2015,2,6,3131

In [57]:
X_train = X_train.drop(columns=["policy_bind_date", "incident_date"])
X_test = X_test.drop(columns=["policy_bind_date", "incident_date"])

In [58]:
print("X_train:", X_train.shape)
print("X_test :", X_test.shape)

X_train: (800, 39)
X_test : (200, 39)

In [59]:
numeric_cols = X_train.select_dtypes(include=["int64", "float64"]).columns
categorical_cols = X_train.select_dtypes(include=["object", "str"]).columns

print("Numerical:", len(numeric_cols))
print("Categorical:", len(categorical_cols))

Numerical: 17
Categorical: 17

In [60]:
print("Numerical columns:")
print(list(numeric_cols))

print("\nCategorical columns:")
print(list(categorical_cols))

Numerical columns:
['months_as_customer', 'age', 'policy_deductable', 'policy_annual_premium', 'umbrella_limit', 'capital-gains', 'capital-loss', 'incident_hour_of_the_day', 'number_of_vehicles_involved', 'bodily_injuries', 'witnesses', 'total_claim_amount', 'injury_claim', 'property_claim', 'vehicle_claim', 'auto_year', 'policy_duration_days']

Categorical columns:
['policy_state', 'policy_csl', 'insured_sex', 'insured_education_level', 'insured_occupation', 'insured_hobbies', 'insured_relationship', 'incident_type', 'collision_type', 'incident_severity', 'authorities_contacted', 'incident_state', 'incident_city', 'property_damage', 'police_report_available', 'auto_make', 'auto_model']

In [61]:
preprocessor = ColumnTransformer(
    transformers=[
        ("num", StandardScaler(), numeric_cols),
        ("cat", OneHotEncoder(handle_unknown="ignore"), categorical_cols)
    ]
)

NameError: name 'ColumnTransformer' is not defined

In [62]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder, StandardScaler

In [63]:
preprocessor = ColumnTransformer(
    transformers=[
        ("num", StandardScaler(), numeric_cols),
        ("cat", OneHotEncoder(handle_unknown="ignore"), categorical_cols)
    ]
)

In [64]:
X_train_processed = preprocessor.fit_transform(X_train)

TypeError: Encoders require their input argument must be uniformly strings or numbers. Got ['int', 'str']

In [65]:
for col in categorical_cols:
    types = X_train[col].dropna().map(type).value_counts()
    if len(types) > 1:
        print(col)
        print(types)

auto_model
auto_model
<class 'str'>    759
<class 'int'>     41
Name: count, dtype: int64

In [66]:
X_train["auto_model"] = X_train["auto_model"].astype(str)
X_test["auto_model"] = X_test["auto_model"].astype(str)

In [67]:
print(X_train["auto_model"].map(type).value_counts())

auto_model
<class 'str'>    800
Name: count, dtype: int64

In [68]:
X_train_processed = preprocessor.fit_transform(X_train)

In [69]:
X_test_processed = preprocessor.transform(X_test)

In [70]:
print("Processed X_train:", X_train_processed.shape)
print("Processed X_test :", X_test_processed.shape)

Processed X_train: (800, 162)
Processed X_test : (200, 162)