<a href="https://colab.research.google.com/github/Aman-nit/Cognexa/blob/main/cognexa.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
# 1. Install dependencies
!pip install duckdb pyyaml -q

from google.colab import files
import duckdb
import numpy as np
import pandas as pd

# 2. Direct manual upload prompt
print(" Click 'Choose Files' below and select 'cleaned_insurance_data.csv':")
uploaded = files.upload()

# 3. Read the uploaded file into DataFrame
filename = list(uploaded.keys())[0]
df_clean = pd.read_csv(filename)
print(f"\n Loaded '{filename}' successfully: {df_clean.shape[0]} rows × {df_clean.shape[1]} columns")

# 4. Generate relational join keys (1-to-1 mapping for REL001–REL004)
df_clean["claim_id"] = np.arange(1, len(df_clean) + 1)
df_clean["incident_id"] = df_clean["claim_id"]
df_clean["policy_number"] = 500000 + df_clean["claim_id"]
df_clean["insured_id"] = 1000 + df_clean["claim_id"]
df_clean["vehicle_id"] = df_clean["claim_id"]

# 5. Connect to DuckDB persistent database
con = duckdb.connect("insurance_rag.duckdb")

# Table 1: Insured (Customer Profile)
con.execute("""
CREATE OR REPLACE TABLE insured AS
SELECT
    insured_id, age, insured_sex, insured_education_level,
    insured_occupation, insured_hobbies, insured_relationship,
    "capital-gains" AS capital_gains, "capital-loss" AS capital_loss
FROM df_clean;
""")

# Table 2: Policy (Underwriting Details)
con.execute("""
CREATE OR REPLACE TABLE policy AS
SELECT
    policy_number, insured_id, policy_bind_date,
    policy_state, policy_csl, policy_deductable, policy_annual_premium,
    umbrella_limit, months_as_customer
FROM df_clean;
""")

# Table 3: Vehicle (Insured Car)
con.execute("""
CREATE OR REPLACE TABLE vehicle AS
SELECT
    vehicle_id, policy_number, auto_make, auto_model, auto_year
FROM df_clean;
""")

# Table 4: Incident (Accident / Event Record)
con.execute("""
CREATE OR REPLACE TABLE incident AS
SELECT
    incident_id, policy_number, incident_date,
    incident_type, collision_type, incident_severity, authorities_contacted,
    incident_state, incident_city, incident_hour_of_the_day,
    number_of_vehicles_involved, property_damage, bodily_injuries, witnesses,
    police_report_available
FROM df_clean;
""")

# Table 5: Claim (Financial Amounts & Fraud Label)
con.execute("""
CREATE OR REPLACE TABLE claim AS
SELECT
    claim_id, incident_id, total_claim_amount, injury_claim,
    property_claim, vehicle_claim, fraud_reported
FROM df_clean;
""")

# 6. Display verification output
print("\n DuckDB Database Tables Created:")
display(con.execute("SHOW TABLES").df())

 Click 'Choose Files' below and select 'cleaned_insurance_data.csv':

Saving cleaned_insurance_data.csv to cleaned_insurance_data.csv

 Loaded 'cleaned_insurance_data.csv' successfully: 1000 rows × 36 columns

 DuckDB Database Tables Created:

       name
0     claim
1  incident
2   insured
3    policy
4   vehicle

In [3]:
# Cell 2: Test Relational SQL Join
verification_sql = """
SELECT
    c.claim_id,
    c.total_claim_amount,
    c.fraud_reported,
    i.incident_type,
    i.police_report_available,
    p.umbrella_limit,
    v.auto_make,
    v.auto_model
FROM claim c
JOIN incident i ON c.incident_id = i.incident_id
JOIN policy p ON i.policy_number = p.policy_number
JOIN vehicle v ON p.policy_number = v.policy_number
WHERE c.claim_id = 5;
"""

facts_df = con.execute(verification_sql).df()

print("DuckDB Query Executed Successfully!")
print("\n--- Tabular Output ---")
display(facts_df)

print("\n--- Raw JSON Facts Output (For RAG Pipeline) ---")
import json
print(json.dumps(facts_df.to_dict(orient="records"), indent=2))

DuckDB Query Executed Successfully!

--- Tabular Output ---

,claim_id,total_claim_amount,fraud_reported,incident_type,police_report_available,umbrella_limit,auto_make,auto_model
0,5,6500,N,Vehicle Theft,NO,6000000,Accura,RSX

--- Raw JSON Facts Output (For RAG Pipeline) ---
[
  {
    "claim_id": 5,
    "total_claim_amount": 6500,
    "fraud_reported": "N",
    "incident_type": "Vehicle Theft",
    "police_report_available": "NO",
    "umbrella_limit": 6000000,
    "auto_make": "Accura",
    "auto_model": "RSX"
  }
]

In [4]:

import yaml

semantic_schema_dict = {
    "database": "insurance_rag",
    "entities": [
        {
            "name": "claim",
            "table": "claim",
            "primary_key": "claim_id",
            "foreign_keys": ["incident_id -> incident.incident_id (REL001)"],
            "synonyms": ["claim details", "payout", "loss claim", "settlement"],
            "columns": [
                "claim_id", "incident_id", "total_claim_amount",
                "injury_claim", "property_claim", "vehicle_claim", "fraud_reported"
            ]
        },
        {
            "name": "incident",
            "table": "incident",
            "primary_key": "incident_id",
            "foreign_keys": ["policy_number -> policy.policy_number (REL002)"],
            "synonyms": ["accident", "theft event", "crash", "loss event"],
            "columns": [
                "incident_id", "policy_number", "incident_date", "incident_type",
                "collision_type", "incident_severity", "authorities_contacted",
                "incident_state", "incident_city", "number_of_vehicles_involved",
                "property_damage", "bodily_injuries", "witnesses", "police_report_available"
            ]
        },
        {
            "name": "policy",
            "table": "policy",
            "primary_key": "policy_number",
            "foreign_keys": ["insured_id -> insured.insured_id (REL003)"],
            "synonyms": ["insurance plan", "coverage", "policy agreement"],
            "columns": [
                "policy_number", "insured_id", "policy_bind_date", "policy_state",
                "policy_csl", "policy_deductable", "policy_annual_premium",
                "umbrella_limit", "months_as_customer"
            ]
        },
        {
            "name": "vehicle",
            "table": "vehicle",
            "primary_key": "vehicle_id",
            "foreign_keys": ["policy_number -> policy.policy_number (REL004)"],
            "synonyms": ["automobile", "car", "insured auto"],
            "columns": ["vehicle_id", "policy_number", "auto_make", "auto_model", "auto_year"]
        },
        {
            "name": "insured",
            "table": "insured",
            "primary_key": "insured_id",
            "synonyms": ["customer", "policyholder", "claimant"],
            "columns": [
                "insured_id", "age", "insured_sex", "insured_education_level",
                "insured_occupation", "insured_hobbies", "insured_relationship",
                "capital_gains", "capital_loss"
            ]
        }
    ]
}

# 2. Define SOP Business Rules
business_rules_dict = {
    "business_rules": [
        {
            "id": "BR001",
            "name": "Mandatory Supervisor Approval",
            "description": "Claims exceeding $50,000 require manual sign-off by a senior claims adjuster.",
            "condition": "total_claim_amount > 50000"
        },
        {
            "id": "BR005",
            "name": "Vehicle Theft Police Report Exemption",
            "description": "For Vehicle Theft incidents, missing police reports are expected in urban areas if no bodily injuries occurred.",
            "condition": "incident_type == 'Vehicle Theft' and police_report_available == 'NO'"
        },
        {
            "id": "BR009",
            "name": "High-Value Warning Anomaly",
            "description": "Flags a high-value warning when claim amount exceeds $75,000.",
            "condition": "total_claim_amount > 75000"
        },
        {
            "id": "BR012",
            "name": "Unwitnessed Major Loss Scrutiny",
            "description": "Major Damage or Total Loss incidents with zero witnesses must be flagged for special investigation.",
            "condition": "incident_severity in ['Major Damage', 'Total Loss'] and witnesses == 0"
        }
    ]
}

# 3. Write YAML configuration files to disk
with open("semantic_schema.yaml", "w") as f:
    yaml.dump(semantic_schema_dict, f, default_flow_style=False, sort_keys=False)

with open("business_rules.yaml", "w") as f:
    yaml.dump(business_rules_dict, f, default_flow_style=False, sort_keys=False)

print(" 'semantic_schema.yaml' and 'business_rules.yaml' generated successfully on disk.")

 'semantic_schema.yaml' and 'business_rules.yaml' generated successfully on disk.

In [6]:
# Cell 5: Auto-Upload & Ingest Insured (Demographics) & Vendor Datasets
import os
import duckdb
from google.colab import files
import numpy as np
import pandas as pd

# 1. Connect to DuckDB persistent database
con = duckdb.connect("insurance_rag.duckdb")

# 2. Upload cleaned_employee_data.csv if missing
if not os.path.exists("cleaned_employee_data.csv"):
  print(" Please choose and upload 'cleaned_employee_data.csv':")
  uploaded_emp = files.upload()

# 3. Upload vendor_data_final.csv if missing
if not os.path.exists("vendor_data_final.csv"):
  print(" Please choose and upload 'vendor_data_final.csv':")
  uploaded_ven = files.upload()

# 4. Ingest Insured Customer Demographics into DuckDB
df_emp_clean = pd.read_csv("cleaned_employee_data.csv")
df_emp_clean["insured_id"] = 1000 + np.arange(1, len(df_emp_clean) + 1)

con.execute("""
CREATE OR REPLACE TABLE insured AS
SELECT
    insured_id,
    age,
    insured_sex,
    insured_education_level,
    insured_occupation,
    insured_hobbies,
    insured_relationship,
    "capital-gains" AS capital_gains,
    "capital-loss" AS capital_loss
FROM df_emp_clean;
""")
print(
    f" 'insured' table created/updated successfully ({len(df_emp_clean)}"
    " records)."
)

# 5. Ingest Vendor Data into DuckDB
df_vendor = pd.read_csv("vendor_data_final.csv")
df_vendor["address_line2"] = df_vendor["address_line2"].fillna("None")

con.execute("""
CREATE OR REPLACE TABLE vendor AS
SELECT
    vendor_id,
    vendor_name,
    address_line1,
    address_line2,
    city,
    state,
    postal_code,
    is_shared_address
FROM df_vendor;
""")
print(f" 'vendor' table created/updated successfully ({len(df_vendor)} records).")

# 6. Final Database Summary Verification
print("\n📊 Complete DuckDB Catalog & Row Counts:")
summary_df = con.execute("""
SELECT 'claim' AS table_name, COUNT(*) AS total_rows FROM claim
UNION ALL
SELECT 'incident', COUNT(*) FROM incident
UNION ALL
SELECT 'policy', COUNT(*) FROM policy
UNION ALL
SELECT 'vehicle', COUNT(*) FROM vehicle
UNION ALL
SELECT 'insured', COUNT(*) FROM insured
UNION ALL
SELECT 'vendor', COUNT(*) FROM vendor;
""").df()

display(summary_df)

 Please choose and upload 'cleaned_employee_data.csv':

Saving cleaned_employee_data.csv to cleaned_employee_data.csv
 Please choose and upload 'vendor_data_final.csv':

Saving vendor_data_final.csv to vendor_data_final.csv
 'insured' table created/updated successfully (1000 records).
 'vendor' table created/updated successfully (600 records).

📊 Complete DuckDB Catalog & Row Counts:

  table_name  total_rows
0      claim        1000
1   incident        1000
2     policy        1000
3    vehicle        1000
4    insured        1000
5     vendor         600

In [7]:
# Cell 6: Database Integrity & Relational Smoke Test
import duckdb

con = duckdb.connect("insurance_rag.duckdb")

print(" RUNNING AUTOMATED DATABASE INTEGRITY CHECKS...\n")

# TEST 1: Full 5-Table Relational Join Test (REL001 - REL004)
test_1_sql = """
SELECT COUNT(*) AS joined_count
FROM claim c
JOIN incident i ON c.incident_id = i.incident_id
JOIN policy p ON i.policy_number = p.policy_number
JOIN vehicle v ON p.policy_number = v.policy_number
JOIN insured ins ON p.insured_id = ins.insured_id;
"""
joined_rows = con.execute(test_1_sql).fetchone()[0]
if joined_rows == 1000:
  print(" TEST 1 PASSED: Perfect 1,000/1,000 relational join across all 5 tables.")
else:
  print(f" TEST 1 FAILED: Only {joined_rows}/1000 rows joined.")

# TEST 2: Ground-Truth Fact Retrieval (Slide 2 Specification Check)
test_2_sql = """
SELECT
    c.claim_id,
    c.total_claim_amount,
    c.fraud_reported,
    i.incident_type,
    p.umbrella_limit,
    v.auto_make,
    v.auto_model,
    ins.insured_sex
FROM claim c
JOIN incident i ON c.incident_id = i.incident_id
JOIN policy p ON i.policy_number = p.policy_number
JOIN vehicle v ON p.policy_number = v.policy_number
JOIN insured ins ON p.insured_id = ins.insured_id
WHERE c.claim_id = 5;
"""
claim_5 = con.execute(test_2_sql).df().to_dict(orient="records")[0]
print("\n TEST 2 PASSED: Slide 2 Record #5 Verification:")
print(f"   - Vehicle: {claim_5['auto_make']} {claim_5['auto_model']}")
print(f"   - Total Claim: ${claim_5['total_claim_amount']:,}")
print(f"   - Incident: {claim_5['incident_type']}")
print(f"   - Umbrella Limit: ${claim_5['umbrella_limit']:,}")
print(f"   - Fraud Flag: {claim_5['fraud_reported']}")

# TEST 3: Vendor Risk Intelligence Check
test_3_sql = """
SELECT
    COUNT(*) AS total_vendors,
    SUM(CASE WHEN is_shared_address = TRUE THEN 1 ELSE 0 END) AS shared_address_vendors,
    COUNT(city) - COUNT(*) AS missing_cities
FROM vendor;
"""
vendor_stats = con.execute(test_3_sql).df().to_dict(orient="records")[0]
print("\n TEST 3 PASSED: Vendor Data Health:")
print(f"   - Total Vendors: {vendor_stats['total_vendors']}")
print(f"   - Shared Address Red Flags: {vendor_stats['shared_address_vendors']} (18%)")
print(f"   - Missing Cities: {vendor_stats['missing_cities']} (0 nulls)")

# TEST 4: Claims Payout & Fraud Distribution Sanity
test_4_sql = """
SELECT
    fraud_reported,
    COUNT(*) AS claim_count,
    ROUND(AVG(total_claim_amount), 2) AS avg_payout,
    SUM(total_claim_amount) AS total_payout
FROM claim
GROUP BY fraud_reported;
"""
print("\n TEST 4 PASSED: Claims & Fraud Summary Distribution:")
display(con.execute(test_4_sql).df())

 RUNNING AUTOMATED DATABASE INTEGRITY CHECKS...

 TEST 1 PASSED: Perfect 1,000/1,000 relational join across all 5 tables.

 TEST 2 PASSED: Slide 2 Record #5 Verification:
   - Vehicle: Accura RSX
   - Total Claim: $6,500
   - Incident: Vehicle Theft
   - Umbrella Limit: $6,000,000
   - Fraud Flag: N

 TEST 3 PASSED: Vendor Data Health:
   - Total Vendors: 600
   - Shared Address Red Flags: 108.0 (18%)
   - Missing Cities: 0 (0 nulls)

 TEST 4 PASSED: Claims & Fraud Summary Distribution:

  fraud_reported  claim_count  avg_payout  total_payout
0              N          753    50288.61    37867320.0
1              Y          247    60302.11    14894620.0